services:
  amq:
    image: apache/activemq-artemis:latest
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "61616:61616"  # AMQP
      - "8161:8161"    # Web Console
